name: Scraper

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  scraper:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6
    services:
      firefox:
        image: selenium/standalone-firefox:3.141.59
    env:
      REMOTE_WEBDRIVER_URL: http://firefox:4444/wd/hub
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Scrape
        run: |
          bundle exec rake
        env:
          REMOTE_WEBDRIVER_URL: http://firefox:4444/wd/hub
