name: Scraper

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  scraper:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6
    services:
      hub:
        image: selenium/hub:3.141.59
      firefox:
        image: selenium/node-firefox:3.141.59
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
    steps:
      - uses: actions/checkout@v2
      - name: Scrape
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake REMOTE_WEBDRIVER_URL=http://hub:4444/wd/hub
