name: TeX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Spelling
        uses: reitermarkus/aspell@master
        with:
          files: tex/*.tex
          args: --lang en_GB --mode tex --personal ./tex/aspell.en_GB.pws --add-tex-command PassOptionsToPackage\ pp --add-tex-command texttt\ op --add-tex-command cite\ op --add-tex-command german\ p
      - name: Compile Paper
        uses: reitermarkus/latexmk@master
      - name: Prepare Paper for Publishing
        run: |
          mkdir -p tex/gh-pages
          mv tex/*.pdf tex/gh-pages/
      - name: Publish Paper
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: tex/gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
