name: TeX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Spelling
        uses: reitermarkus/aspell@master
        with:
          files: paper/paper.tex
          args: --lang en_GB --mode tex --personal ./paper/aspell.en_GB.pws --add-tex-command PassOptionsToPackage\ pp --add-tex-command texttt\ op --add-tex-command cite\ op --add-tex-command german\ p
      - name: Compile Paper
        uses: reitermarkus/latexmk@master
      - name: Upload Paper
        uses: actions/upload-artifact@v2
        with:
          name: paper.pdf
          path: paper/paper.pdf
      - name: Prepare Paper for Publishing
        run: |
          mkdir -p paper/gh-pages
          mv paper/paper.pdf paper/gh-pages/
      - name: Publish Paper
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: paper/gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
