name: TeX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Graphs
        run: |
          sudo gem install rake
          rake graphs
      - name: Compile Paper
        uses: reitermarkus/latexmk@master
      - name: Upload Paper
        uses: actions/upload-artifact@v2
        with:
          name: paper.pdf
          path: paper/paper.pdf
